###
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "some@email.com",
  "password": "min5len"
}


###
GET http://localhost:8889/api/quizzes?offset=1&size=10
Authorization: Basic some@email.com min5len


###
GET http://localhost:8889/api/quizzes/completed?page=0
Authorization: Basic some@email.com min5len

###
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic some@email.com min5len

{
  "title": "The Java Logo",
  "text": "What is depicted on the Java logo?",
  "options": ["Robot","Tea leaf","Cup of coffee","Bug"],
  "answer": [2]
}

###
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic some@email.com min5len

{
  "title": "The Kotlin Logo",
  "text": "What is depicted on the Kotlin logo?",
  "options": ["Robot","Capital K","Cup of coffee","Bug"],
  "answer": [1]
}

###
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic some@email.com min5len

{
  "title": "European Capitals",
  "text": "What are the capitals of European countries?",
  "options": ["Kyiv","Paris","Deli","Tokyo"],
  "answer": [0, 1]
}

###
GET http://localhost:8889/api/quizzes/1
Authorization: Basic some@email.com min5len

###
POST http://localhost:8889/api/quizzes/1/solve
Content-Type: application/json
Authorization: Basic some@email.com min5len

{
  "answer": [2]
}

###
POST http://localhost:8889/api/quizzes/4/solve
Content-Type: application/json
Authorization: Basic some@email.com min5len

{
  "answer": [1, 0]
}