###
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "some1@email.com",
  "password": "min5len"
}

###
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "some2@email.com",
  "password": "min5len"
}

###
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "wrong.email",
  "password": "min5len"
}


###
GET http://localhost:8889/api/quizzes
Authorization: Basic some1@email.com min5len

###
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic some1@email.com min5len

{
  "title": "The Java Logo",
  "text": "What is depicted on the Java logo?",
  "options": ["Robot","Tea leaf","Cup of coffee","Bug"],
  "answer": [2]
}

###
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic some1@email.com min5len

{
  "title": "The Kotlin Logo",
  "text": "What is depicted on the Kotlin logo?",
  "options": ["Robot","Capital K","Cup of coffee","Bug"],
  "answer": [1]
}

###
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic some2@email.com min5len

{
  "title": "European Capitals",
  "text": "What are the capitals of European countries?",
  "options": ["Kyiv","Paris","Deli","Tokyo"],
  "answer": [0, 1]
}

###
GET http://localhost:8889/api/quizzes/1
Authorization: Basic some1@email.com min5len

###
POST http://localhost:8889/api/quizzes/1/solve
Content-Type: application/json
Authorization: Basic some1@email.com min5len

{
  "answer": [2]
}

###
POST http://localhost:8889/api/quizzes/3/solve
Content-Type: application/json
Authorization: Basic some1@email.com min5len

{
  "answer": [1, 0]
}

###
DELETE http://localhost:8889/api/quizzes/1
Authorization: Basic some1@email.com min5len

###
DELETE http://localhost:8889/api/quizzes/2
Authorization: Basic some2@email.com min5len

###
DELETE http://localhost:8889/api/quizzes/3
Authorization: Basic some2@email.com min5len