###
# create USER_1
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "user1@email.com",
  "password": "password"
}

###
# create USER_2
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "user2@email.com",
  "password": "password"
}

###
# get 400 error with invalid e-mail
POST http://localhost:8889/api/register
Content-Type: application/json

{
  "email": "wrong.email",
  "password": "min5len"
}


###
# get list of created quizzes (default is page 0 size 10)
GET http://localhost:8889/api/quizzes
Authorization: Basic user1@email.com password

###
# get list of created quizzes, page=1 (empty)
GET http://localhost:8889/api/quizzes?page=1
Authorization: Basic user1@email.com password

###
# create a quiz item #1 by USER_1
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic user1@email.com password

{
  "title": "The Java Logo",
  "text": "What is depicted on the Java logo?",
  "options": ["Robot","Tea leaf","Cup of coffee","Bug"],
  "answer": [2]
}

###
# create a quiz item #2 by USER_2
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic user2@email.com password

{
  "title": "The Kotlin Logo",
  "text": "What is depicted on the Kotlin logo?",
  "options": ["Robot","Capital K","Cup of coffee","Bug"],
  "answer": [1]
}

###
# create a quiz item #3 by USER_1
POST http://localhost:8889/api/quizzes
Content-Type: application/json
Authorization: Basic user1@email.com password

{
  "title": "European Capitals",
  "text": "What are the capitals of European countries?",
  "options": ["Kyiv","Paris","Deli","Tokyo"],
  "answer": [0, 1]
}

###
# USER_1 gets quiz #1
GET http://localhost:8889/api/quizzes/1
Authorization: Basic user1@email.com password

###
# USER_2 gets quiz #1
GET http://localhost:8889/api/quizzes/1
Authorization: Basic user2@email.com password

###
# USER_1 correctly solves quiz #1
POST http://localhost:8889/api/quizzes/1/solve
Content-Type: application/json
Authorization: Basic user1@email.com password

{
  "answer": [2]
}

###
# USER_2 correctly solves quiz #3
POST http://localhost:8889/api/quizzes/3/solve
Content-Type: application/json
Authorization: Basic user2@email.com password

{
  "answer": [1, 0]
}

###
# USER_2 correctly solves quiz #2
POST http://localhost:8889/api/quizzes/2/solve
Content-Type: application/json
Authorization: Basic user2@email.com password

{
  "answer": [1]
}

###
# completions for USER_2
GET http://localhost:8889/api/quizzes/completed?page=0
Authorization: Basic user2@email.com password

###
# completions for USER_1
GET http://localhost:8889/api/quizzes/completed?page=0
Authorization: Basic user1@email.com password